# note that this site.yml file is for local building and testing only
site:
  title: ownCloud Android App Documentation
  url: https://doc.owncloud.com
  start_page: android::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    # asciidoctor prefix for section IDs
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
    # Custom attribute page-component-build-list
    # Only embed named opengraph images in docs-ui via partials/head-meta-opengraph.hbs
    page-component-build-list: 'docs, server, ocis, webui, user, desktop, ios-app, android'
#   android
    latest-android-version: '4.1'
    previous-android-version: '4.0'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js
